### ISSUE TITLE
optimization: remove tmp files and dir

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/Omeka-S-Module-LinkedDataSets#11]
currently tmp files and directory aren't deleted

delete file after merge:
https://github.com/netwerk-digitaal-erfgoed/Omeka-S-Module-LinkedDataSets/blob/7e3902241da7469bd56fa81f1c4dc0c257de678f/src/Application/Job/DataDumpJob.php#L199

tmp dir after datadump has been processed

**Comment by parijke** [comment]
Fixed in https://github.com/netwerk-digitaal-erfgoed/Omeka-S-Module-LinkedDataSets/commit/0be75f99b591de496e9c9e69ccaaa82aaab51f8f

**Comment by coret** [comment]
I get the following error when the Datadump job is started:
```
Laminas\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "LDS\FilesystemService" to a factory; are you certain you provided it during configuration? in /home/**/omeka-s-4.0.0/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:559
Stack trace:
#0 /home/**/omeka-s-4.0.0/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(614): Laminas\ServiceManager\ServiceManager->getFactory()
#1 /home/**/omeka-s-4.0.0/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#2 /home/**/omeka-s-modules/LinkedDataSets/src/Application/Job/DataDumpJob.php(89): Laminas\ServiceManager\ServiceManager->get()
#3 /home/**/omeka-s-4.0.0/application/src/Job/DispatchStrategy/Synchronous.php(33): LinkedDataSets\Application\Job\DataDumpJob->__construct()
#4 /home/**/omeka-s-modules/Log/src/Job/Dispatcher.php(78): Omeka\Job\DispatchStrategy\Synchronous->send()
#5 /home/**/omeka-s-4.0.0/application/data/scripts/perform-job.php(66): Log\Job\Dispatcher->send()
#6 {main}
```

**Comment by parijke** [comment]
Ik ga het checken Bob
